// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"api-core/internal/app/auth"
	"api-core/internal/app/chat"
	"api-core/internal/app/friend"
	"api-core/internal/app/user"
	"api-core/internal/repositories"
	"api-core/internal/routes"
	"api-core/pkg/cache"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp khởi tạo toàn bộ ứng dụng với database và cache
func InitializeApp(db *gorm.DB, cacheClient cache.Cache) (*routes.Controllers, error) {
	userRepository := repository.NewUserRepository(db)
	storageManager, err := ProvideStorageManager()
	if err != nil {
		return nil, err
	}
	client, err := ProvideFCMClient()
	if err != nil {
		return nil, err
	}
	service := user.NewService(userRepository, cacheClient, storageManager, client)
	handler := user.NewHandler(service)
	manager := ProvideJWTManager()
	blacklist := ProvideJWTBlacklist(cacheClient)
	authService := auth.NewService(userRepository, manager, blacklist, storageManager)
	authHandler := auth.NewHandler(authService)
	friendRequestRepository := repository.NewFriendRequestRepository(db)
	friendshipRepository := repository.NewFriendshipRepository(db)
	friendService := friend.NewService(friendRequestRepository, friendshipRepository, userRepository, db)
	friendHandler := friend.NewHandler(friendService)
	conversationRepository := repository.NewConversationRepository(db)
	conversationParticipantRepository := repository.NewConversationParticipantRepository(db)
	messageRepository := repository.NewMessageRepository(db)
	chatService := chat.NewService(conversationRepository, conversationParticipantRepository, messageRepository, friendshipRepository, userRepository, db)
	chatHandler := chat.NewHandler(chatService)
	cacheInterface := ProvideCacheInterface(cacheClient)
	controllers := routes.NewControllers(handler, authHandler, friendHandler, chatHandler, manager, blacklist, cacheInterface)
	return controllers, nil
}

// wire.go:

// ProvideCacheInterface provides cache interface for rate limiting
func ProvideCacheInterface(cacheClient cache.Cache) routes.CacheInterface {
	return cacheClient
}
