// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"anhnq/api-core/internal/app/auth"
	"anhnq/api-core/internal/app/user"
	repository "anhnq/api-core/internal/repositories"
	"anhnq/api-core/internal/routes"
	"anhnq/api-core/pkg/cache"

	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB, cacheClient cache.Cache) *routes.Controllers {
	manager := ProvideJWTManager()
	blacklist := ProvideJWTBlacklist(cacheClient)
	userRepository := repository.NewUserRepository(db)
	authRepository := repository.NewAuthRepository(db)
	userService := user.NewService(userRepository, cacheClient)
	handler := user.NewHandler(userService)
	service := auth.NewService(authRepository, manager, blacklist)
	authHandler := auth.NewHandler(service)
	controllers := routes.NewControllers(handler, authHandler, manager, blacklist)
	return controllers
}
